#pragma once
#include "BindingThunk.hpp"
#include "safetyhook/inline_hook.hpp"
#include "safetyhook/ptmf_helper.hpp"

#include <variant>

namespace safetyhook {
/** @brief An inline hook whose destination is a member function with a specific instance.
 * @note The instance must outlive the hook.
 * @attention Detouring functions that return by value but are implicitly references at the ABI level will not work.
 */
class SAFETYHOOK_API InlineToMemberFunctionHook {
public:
    using IMFHError = std::variant<InlineHook::Error, BindingThunk::FThunkError>;

    /// @brief Create an inline hook whose destination is a member function with a specific instance.
    /// @param target The address of the function to hook.
    /// @param instance The instance to bind to; destination must be a member of instance's type.
    /// @param flags The flags to use.
    /// @tparam Destination The pointer to the member function to detour to.
    /// @return The InlineToMemberFunctionHook or an InlineToMemberFunctionHook::Error if an error occurred.
    /// @note This will use the default global Allocator.
    /// @attention Detouring functions that return by value but are implicitly references at the ABI level will not work.
    template <typename Target, auto Destination>
        requires PointerToMemberFunction<Destination>
    [[nodiscard]] static std::expected<InlineToMemberFunctionHook, IMFHError> create(Target target,
        PTMFHelper<decltype(Destination)>::ClassType* instance, InlineHook::Flags flags = InlineHook::Flags::Default) {
        using Helper = PTMFHelper<decltype(Destination)>;
        const auto signature = Helper::GetSignature();
        if (!signature)
            return std::unexpected<IMFHError>(signature.error());
        return create(reinterpret_cast<void*>(target), reinterpret_cast<void*>(instance),
            reinterpret_cast<void*>(&Helper::template StaticInvoker<Destination>), signature, flags);
    }

    /**
     * @brief Create an inline hook whose destination is a member function with a specific instance.
     * @param target The address of the function to hook.
     * @param instance The instance to bind to.
     * @param static_invoker The static invoker of the member function. If not autogenerated from the templated version
     * of @ref create, it must match the static signature of the member function (`this` pointer as first parameter,
     * with arguments as remaining parameters) and call the member function with the given `this` and arguments.
     * @param signature The built ABISignature to generate the thunk with.
     * @param flags The flags to use.
     * @return The InlineToMemberFunctionHook or an InlineToMemberFunctionHook::Error if an error occurred.
     * @note This will use the default global Allocator.
     * @attention Detouring functions that return by value but are implicitly references at the ABI level will not work.
     */
    [[nodiscard]] static std::expected<InlineToMemberFunctionHook, IMFHError> create(void* target, void* instance,
        void* static_invoker, const BindingThunk::ABISignature& signature,
        InlineHook::Flags flags = InlineHook::Flags::Default);

    InlineToMemberFunctionHook() = default;
    InlineToMemberFunctionHook(InlineToMemberFunctionHook&& Other) noexcept = default;
    InlineToMemberFunctionHook& operator=(InlineToMemberFunctionHook&& Other) noexcept = default;
    InlineToMemberFunctionHook(const InlineToMemberFunctionHook& Other) = delete;
    InlineToMemberFunctionHook& operator=(const InlineToMemberFunctionHook& Other) = delete;

    /// @brief Enable the hook.
    [[nodiscard]] std::expected<void, InlineHook::Error> enable();

    /// @brief Disable the hook.
    [[nodiscard]] std::expected<void, InlineHook::Error> disable();

    /// @brief Check if the hook is enabled.
    [[nodiscard]] bool enabled() const;

private:
    InlineHook m_hook{};
    BindingThunk::FThunkPtr m_binder{};
};
} // namespace safetyhook
